DECLARE @BKDATE VARCHAR(64), @BKPATH VARCHAR(64), @BKNAME VARCHAR(128);
SELECT @BKDATE = CONVERT(VARCHAR, GETDATE(), 112); --Format: YYYYMMDD
SELECT @BKPATH = N'D:\236DB_Backup\Shipdt\DB\' + @BKDATE + '.bak';
SELECT @BKDATE = N'Shipdt-完整 資料庫 備份' + ' - ' + @BKDATE;
BACKUP DATABASE [Shipdt] TO  DISK = @BKPATH WITH NOFORMAT, NOINIT,  NAME = @BKDATE, SKIP, NOREWIND, NOUNLOAD,  STATS = 10
GO
